version: "3.9"

networks:
  appnet:
    ipam:
      config:
        - subnet: "172.31.1.0/16"

services:

  # Nodo principale
  earth:
    image: couchbase/server
    volumes:
      - ./couchbase/node3:/opt/couchbase/var
    networks:
      appnet:
        ipv4_address: "172.31.1.1"
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"


  venus:
    image: couchbase/server
    volumes:
      - ./couchbase/node2:/opt/couchbase/var
    networks:
      appnet:
        ipv4_address: "172.31.1.2"



  mercury:
    image: couchbase/server
    volumes:
      - ./couchbase/node1:/opt/couchbase/var
    networks:
      appnet:
        ipv4_address: "172.31.1.3"